spring.application.name=TestProjectForPractice

spring.datasource.url=jdbc:postgresql://localhost:5435/SmartZone?currentSchema=jdbo
spring.datasource.username=postgres
spring.datasource.password=Zmxncbv1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=jdbo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

springdoc.groups.enabled=true

spring.data.web.pageable.default-page-size=10
